# Generated by Django 3.2.3 on 2023-09-29 04:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cats', '0004_cat_unique_name_owner'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='cat',
            name='unique_name_owner',
        ),
    ]
